---
#fqdn: innad.tk
# ansible_fqdn from ansible setup
lets_email: "{{ vault_lets_email }}"
venv_dir: flask
remote_user_my: "{{ vault_remote_user_my }}"
app_user: "{{ vault_app_user }}"
#home_dir: "{{ ansible_user_dir }}"
home_dir: /opt/{{ app_user }}
pkg_curs: curs-17.3.8.dev1-py3-none-any.whl
app_spiders: spiders-17.3.2.dev1-py3-none-any.whl
pkg_curs_auto: curs_auto-17.3.7.dev1-py3-none-any.whl
conf_dir: /etc/curs
# TODO: replace in plays hardcoded python3.6 on python_ver
python_ver: python3.7

# nginx
static_path: /var/www/curs/static
ssl_certificate: /etc/nginx/ssl/nginx.crt
ssl_certificate_key: /etc/nginx/ssl/nginx.key
# vars for curs app
curs:
  after:
    - syslog.target
    - network.target
    - mongodb.service
  requires:
    - mongodb.service
    - nginx.service
  # /var/run need spesial write permitions
  pidfile: /tmp/curs.pid
  cmd: "{{ home_dir }}/{{ venv_dir }}/bin/uwsgi --ini {{ home_dir }}/{{ venv_dir }}/.curs/uwsgi.ini --venv {{ home_dir }}/{{ venv_dir }} --daemonize {{ home_dir }}/{{ venv_dir }}/curs_uwsgi.log"

# vars for cursauto script
cursauto:
  after:
    - syslog.target
    - network.target
    - mongodb.service
  requires:
    - mongodb.service
  cmd: "{{ home_dir }}/{{ venv_dir }}/bin/curs_auto"

