---
- hosts: ec2
  vars:
#    ssl_certificate_key: /etc/nginx/ssl/nginx.key
  vars_files:
    - vars/main.yml
  roles:
# or put in meta into dependencies:
    - role: mongoCleaner
      tags:
        - mongoCleaner
