---
- hosts: ec2-inna
  vars:
#    ssl_certificate_key: /etc/nginx/ssl/nginx.key
  vars_files:
    - vars/main.yml
  roles:
# or put in meta into dependencies:
    - role: linux
      tags:
        - linux
    - role: mongoCleaner
      tags:
        - mongoCleaner
    - role: ft
      tags:
        - ft
    - role: bi
      tags:
        - bi
